# Generated by Django 4.1.7 on 2024-07-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(default='default file', max_length=512)),
                ('file', models.FileField(default='', upload_to='file/<django.db.models.fields.AutoField>')),
                ('content', models.TextField(default='')),
            ],
            options={
                'db_table': 'files',
            },
        ),
    ]
