# Generated by Django 4.1.7 on 2024-07-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='doc_id',
            field=models.IntegerField(default=0),
        ),
    ]
