# Generated by Django 4.1.7 on 2024-07-13 13:28

from django.db import migrations, models
import file.models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_file_doc_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='type',
            field=models.CharField(default='img', max_length=50),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(default='', upload_to=file.models.upload_to),
        ),
    ]
