# Generated by Django 5.0.6 on 2024-05-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.IntegerField(default=0)),
                ('content', models.TextField(default='')),
            ],
            options={
                'db_table': 'Document',
            },
        ),
    ]
