# Generated by Django 4.1.7 on 2024-06-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0002_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='is_collect',
            field=models.BooleanField(default=False),
        ),
    ]
