# Generated by Django 4.1.7 on 2024-06-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0003_doc_is_collect'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(default=0)),
                ('doc', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Collection',
            },
        ),
        migrations.RemoveField(
            model_name='doc',
            name='is_collect',
        ),
    ]
