# Generated by Django 5.0.6 on 2024-05-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
