# Generated by Django 4.1.7 on 2024-05-30 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_team_is_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='creator',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
