# Generated by Django 4.1.7 on 2024-05-30 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_team_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='creator',
            field=models.IntegerField(),
        ),
    ]
