# Generated by Django 5.0.6 on 2024-05-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(default='default user', max_length=32)),
                ('password', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=32)),
                ('icon', models.FileField(default='', upload_to='icon')),
                ('isVIP', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
